from typing import Protocol


class StorageProvider(Protocol):
    def read(self, path: str) -> bytes: ...
    def write(self, path: str, data: bytes) -> None: ...
    def atomic_write(self, path: str, data: bytes) -> None: ...
    def exists(self, path: str) -> bool: ...
    def delete(self, path: str) -> None: ...
    def list(self, prefix: str) -> list[str]: ...
    def append(self, path: str, data: bytes) -> None: ...
    # Workspace-relative path to an absolute filesystem path. Needed by
    # everything that hands a stored file to something outside the process —
    # a form uploader, an attachment — and already relied on by callers
    # annotated with this protocol.
    def resolve(self, path: str) -> str: ...
