from typing import Protocol


class StorageProvider(Protocol):
    def read(self, path: str) -> bytes: ...
    def write(self, path: str, data: bytes) -> None: ...
    def atomic_write(self, path: str, data: bytes) -> None: ...
    def exists(self, path: str) -> bool: ...
    def delete(self, path: str) -> None: ...
    def list(self, prefix: str) -> list[str]: ...
    def append(self, path: str, data: bytes) -> None: ...
